### ISSUE TITLE
The release-gap-package fails copying the files if the folder has a space in the name

### ISSUE THREAD

**Issue by CAPiedade** [gap-system/ReleaseTools#105]
The folder of my GAP packages is "GAP Packages"

cp: cannot stat '/mnt/c/Users/Claudio/GAP': No such file or directory
cp: cannot stat 'Packages/pkg/corefreesub/tmp/corefreesub-0.4/doc/chap0.html': No such file or directory

**Comment by fingolfin** [comment]
Resolved now
