### ISSUE TITLE
use PackageInfo's README_URL to replace hardcoded "README"

### ISSUE THREAD

**Issue by fingolfin** [gap-system/ReleaseTools#11]
We could try to extract the `README_URL` from the PackageInfo.g, and the filename therein, to use that instead of blindly coping a file named README. This helps projects which use another name, e.g. `README.md`

**Comment by alex-konovalov** [comment]
(+1) gap-distribution/DistributionUpdate/PackageUpdate/PackageInfoTools.g is doing exactly that.

**Comment by fingolfin** [comment]
Ah, https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/PackageInfoTools.g -- I wasn't even really aware of the `gap-distribution`. When was that added? Is it up-to-date, and the one being used?

**Comment by alex-konovalov** [comment]
Of course this is the one being used. This is former content of the `dev` directory that was moved to a separate repository and announced in gap-dev list on March 6th 2015 (in the thread called `GAP Developers manual` - I agree that if one was not following that thread from the beginning, it was easy to overlook). 

We still have https://github.com/gap-system/gap/tree/master/dev/DistributionUpdate because it has gaprsync

**Comment by alex-konovalov** [comment]
P.S. And I was referring to this content sitting in `dev` directory in my talk [Continuous integration, package update mechanism and release management in GAP](http://dx.doi.org/10.6084/m9.figshare.1483506) at the 1st GAP Days.

**Comment by fingolfin** [comment]
Yes, I remember your talk from the 1st GAP days, and I knew about the `dev` directory. I just missed the fact that its contents were moved to a separate repository.

**Comment by fingolfin** [comment]
As a termporary workaround, the `make-dist` script as well as the new `release` script now uses the regex "README*" to match the filename. I will change `release` to use the `README_URL` field; the reason I am holding of on that is that it will also require the user to  modify the gh-pages files to pick up the right file, and I am not yet quite sure whether this can and/or should also be automated (e.g. the README filename could go into the `package.yml` file -- right now it just contains the URL to the README...)
