### ISSUE TITLE
Remind that paths are case sensitive

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/ReleaseTools#38]
Step 3 in the "Initial setup" in README.md uses `~.PackageName` to set up URLs in `PackageInfo.g`. It may be useful to put a reminder that these are case sensitive and you may need to use `LowercaseString(~.PackageName)` if e.g. the `~.PackageName` is `"Example"` but the repository URL has `"example"`.

**Comment by fingolfin** [comment]
The text "note that case matters" has been in that step since 2016-01-15. If you think it could be made clearer, please make a specific suggestion, possibly via PR.
