### ISSUE TITLE
Support images in manuals

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/ReleaseTools#55]
The problem: the `doc` directory of the package has `.png` files, displayed in the manual, but `ReleaseTools` does not copy them into the `gh-pages` branch of the package. Is there a way to specify that they should be copied as well?

**Comment by fingolfin** [comment]
You'd have to add .png in this line https://github.com/gap-system/ReleaseTools/blob/1d9cb19d4e3e13d4a141f2928ea64c43fabc27b2/release#L583

Feel free to submit a PR doing that.

The proper long-term fix is to add some way for packages to perform arbitrary actions when "installing" their manual(s).

**Comment by alex-konovalov** [comment]
Does not seem possible at the moment since only files with these extensions are copied:
https://github.com/gap-system/ReleaseTools/blob/1d9cb19d4e3e13d4a141f2928ea64c43fabc27b2/release#L583

What would be a proper way to allow this?
