### ISSUE TITLE
Attempt to run make distclean before autogen.sh in release-gap-package

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/ReleaseTools#76]
...or something similar/equivalent. This could help make sure that unwanted build files are not included in the release archive.

This idea came about in relation to the discussion on #74; see https://github.com/gap-system/ReleaseTools/issues/74#issuecomment-776044711 in particular.

This would require a little bit of care, since of course not all packages support it.

**Comment by fingolfin** [comment]
Actually I don't follow: normally you can only run `make ANYTHING` after autogen+configure were run.

**Comment by wilfwilson** [comment]
Yes, true. I suppose this would only be useful when a package author attempts to make a release from a directory in which the package is already compiled. If that's not a use case that you want to support, then please feel free to close the issue 🙂
