### ISSUE TITLE
makedoc.g

### ISSUE THREAD

**Issue by jspreer** [gap-system/ReleaseTools#88]
Hi,

Trying to setup release tools for simpcomp and I am getting this error message which I do not know how to address (this is my second attempt, in the first attempt - see https://github.com/simpcomp-team/simpcomp/issues/27 - I used the wrong repository / wrong setup in PackageInfo.g).

Extracting information from PackageInfo.g...
Package simpcomp 2.1.13
Building GAP package documentation (using makedoc.g)
Using archive basename simpcomp-2.1.13
Using GitHub repository simpcomp-team/simpcomp
Using GitHub username simpcomp-team
Using branch master
Using git tag v2.1.13 (derived from ArchiveURL in in PackageInfo.g)

Exporting repository content for tag 'v2.1.13'
Building GAP package documentation for archives (using makedoc.g)
ERROR: there was an error running GAP, see /home/jonathan/apps/gap-4.11.1/pkg/simpcomp/tmp/gap-error.log

==== gap-error.log

Generating documentation in Directory("./doc/")
#I Composing XML document . . .
Error, Did not find chunk objecttypes at /home/jonathan/apps/gap-4.11.1/pkg/GAPDoc-1.6.4/lib/ComposeXML.gi:231 called from

**Comment by alex-konovalov** [comment]
Hi @jspreer - this looks like entirely the  problem with the documentation, it can't find some part of it to assemble the complete document. I will close this issue here, will explain at https://github.com/simpcomp-team/simpcomp/issues/27
